version: "3.9"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    depends_on:
      - php-fpm
    restart: always

  php-fpm:
    image: php:fpm-alpine
    ports:
      - 9000:9000
    volumes:
      - ./src:/var/www/html
      - ./php/99_overwrite.conf:/usr/local/etc/php-fpm.d/99_overwrite.conf
