apiVersion: v1
kind: ConfigMap
metadata:
  name: php-test-nginx
  namespace: shop
data:
  conf: |-
    server {
        index index.php index.html;
        server_name phpfpm.local;
        error_log  /var/log/nginx/error.log;
        access_log /var/log/nginx/access.log;
        root /var/www/html;

        location /nginx_status {
            stub_status;
        }

        location /test {
          default_type text/plain;
          return 200 "document_root=$document_root\nfastcgi_script_name=$fastcgi_script_name\n";
        }

        location ~ ^/php_(status|ping)$ {
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            add_header debug "$document_root$fastcgi_script_name" always;
            include fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;
        }

        location / {
            autoindex on;
            autoindex_exact_size on;
            autoindex_localtime on;
            autoindex_format html;
        }

        location ~ \.html {
            try_files $uri =404;
        }

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }
