apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-test
  namespace: shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-php
  template:
    metadata:
      labels:
        app: nginx-php
    spec:
      volumes:
        - name: content
          configMap:
            name: php-test-content
            defaultMode: 420
        - name: php
          configMap:
            name: php-test-php
            defaultMode: 420
        - name: nginx
          configMap:
            name: php-test-nginx
            items:
              - key: conf
                path: default.conf
            defaultMode: 420
      containers:
        - name: php
          image: php:fpm-alpine
          ports:
            - containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: php
              mountPath: /usr/local/etc/php-fpm.d/99-overwrite.conf
              subPath: 99-overwrite.conf
            - name: content
              mountPath: /var/www/html
        - name: nginx
          image: nginx:alpine-slim
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: nginx
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: content
              mountPath: /var/www/html

